feat: reestruturar o fluxo de trabalho do GitHub Actions para automatizar o processo de renderização e deploy dos livros

diff --git a/.github/workflows/books.yml b/.github/workflows/books.yml
--- a/.github/workflows/books.yml
+++ b/.github/workflows/books.yml
@@ -147,60 +147,13 @@ jobs:
           name: books_renderizados
           path: "./_docs"
 
-  automatizar:
+  books:
     needs: [renderizar]
     runs-on: ubuntu-latest
-    if: needs.detectar.outputs.FOLDERS_LISTA != ''
     environment:
       name: ENVIRONMENT
-    env:
-      TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
-      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
-      USERNAME: ${{ github.repository_owner }}
     steps:
       - name: Clona o Repositório 'BOOKS'
-        uses: actions/checkout@v4
-        with:
-          repository: ${{ env.USERNAME }}/books
-          token: ${{ secrets.GITHUB_TOKEN }}
-          path: books
-          ref: main
-
-      - name: Configura Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.13"
-
-      - name: Instalar dependencias  do python
-        run: |
-          cd books
-          python -m pip install --upgrade pip
-          pip install -r run/requirements.txt
-
-      - name: Baixa artefato dos livros renderizados
-        uses: actions/download-artifact@v4
-        with:
-          name: books_renderizados
-          path: books/book
-
-      - name: Executa script de automatização
-        run: |
-          cd books
-          python run/cleanBooks.py --base-dir book/
-
-      - name: Salva Artefato dos Livros Renderizados
-        uses: actions/upload-artifact@v4
-        with:
-          name: books_automatizar
-          path: "books/book"
-
-  books:
-    needs: [automatizar]
-    runs-on: ubuntu-latest
-    environment:
-      name: ENVIRONMENT
-    steps:
-      - name: Clona o Repositório BOOKS
         uses: actions/checkout@v4
         with:
           repository: ${{ github.repository }}
@@ -208,25 +161,27 @@ jobs:
           ref: main
           path: "."
 
-      - name: Baixa Artefato para GitHub Pages
+      - name: Baixa Artefato para 'GitHub Pages'
         uses: actions/download-artifact@v4
         with:
           name: books_automatizar
-          path: "./book"
+          path: "./books/book"
 
       - name: Configura Python
         uses: actions/setup-python@v4
         with:
           python-version: "3.13"
 
-      - name: Instalar dependencias  do python
+      - name: Instalar dependencias do Python
         working-directory: books
         run: |
-            python -m pip install --upgrade pip
-            pip install -r run/requirements.txt          
+          python -m pip install --upgrade pip
+          pip install -r run/requirements.txt
 
-      - name: Corrigir links dos <head>
+      - name: Corrigir links para GitHub Pages - Books
+        working-directory: books
         run: |
+          # indo para para pasta books/book/
           cd book
           python run/cleanBooks.py --base-dir book/ --base-ac build/ac/books
 
@@ -234,99 +189,104 @@ jobs:
         uses: actions/upload-pages-artifact@v3
         with:
           name: github-pages
-          path: "./book"
+          path: "./books/book"
 
-      - name: Faz deploy para GitHub Pages
+      - name: Faz deploy para GitHub Pages - Books
         uses: actions/deploy-pages@v4
         with:
           artifact_name: github-pages
 
-  estatistica:
-    needs: [automatizar, books]
-    runs-on: ubuntu-latest
-    if: needs.detectar.outputs.FOLDERS_LISTA != ''
-    environment:
-      name: ENVIRONMENT
-    env:
-      FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
-      USERNAME: ${{ github.repository_owner }}
-      USEREMAIL: ${{ secrets.USEREMAIL }}
-      TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
-    steps:
-      - name: Clona o Repositório ESTATISTICA
-        uses: actions/checkout@v4
-        with:
-          ref: book
-          path: estatistica
-          fetch-depth: 0
-          repository: ${{ env.USERNAME }}/estatistica
-          token: ${{ env.TOKEN_REPO_SYNC }}
+  # estatistica:
+  #   needs: [renderizar, books]
+  #   runs-on: ubuntu-latest
+  #   if: needs.detectar.outputs.FOLDERS_LISTA != ''
+  #   environment:
+  #     name: ENVIRONMENT
+  #   env:
+  #     FOLDERS_LISTA: ${{ needs.detectar.outputs.FOLDERS_LISTA }}
+  #     USERNAME: ${{ github.repository_owner }}
+  #     USEREMAIL: ${{ secrets.USEREMAIL }}
+  #     TOKEN_REPO_SYNC: ${{ secrets.TOKEN_REPO_SYNC }}
+  #   steps:
+  #     - name: Clona o Repositório ESTATISTICA
+  #       uses: actions/checkout@v4
+  #       with:
+  #         ref: book
+  #         path: estatistica
+  #         fetch-depth: 0
+  #         repository: ${{ env.USERNAME }}/estatistica
+  #         token: ${{ env.TOKEN_REPO_SYNC }}
 
-      - name: Bixar submodulo
+  #     - name: Bixar submodulo book
+  #       uses: actions/checkout@v4
+  #       with:
+  #         repository: ${{ env.USERNAME }}/books
+  #         ref: main
+  #         path: book
 
-      - name: Garante que a branch book existe e faz checkout
-        working-directory: estatistica
-        run: |
-          if ! git rev-parse --verify book >/dev/null 2>&1; then
-            git checkout --orphan book
-            git rm -rf .
-            git commit --allow-empty -m "Cria branch book inicial"
-            git push origin book
-          else
-            git checkout book
-          fi
+  #     - name: Garante que a branch book existe e faz checkout
+  #       working-directory: estatistica
+  #       run: |
+  #         if ! git rev-parse --verify book >/dev/null 2>&1; then
+  #           git checkout --orphan book
+  #           git rm -rf .
+  #           git commit --allow-empty -m "Cria branch book inicial"
+  #           git push origin book
+  #         else
+  #           git checkout book
+  #         fi
 
-      - name: Baixa artefato dos livros renderizados
-        uses: actions/download-artifact@v4
-        with:
-          name: books_automatizar
-          path: _books
+  #     - name: Baixa artefato dos livros renderizados
+  #       uses: actions/download-artifact@v4
+  #       with:
+  #         name: books_automatizar
+  #         path: _books
 
-      - name: Sincroniza arquivos do artefato com a branch book
-        run: |
-          rsync -av --update --delete _books/ estatistica/book/
+  #     - name: Sincroniza arquivos do artefato com a branch book
+  #       run: |
+  #         rsync -av --update --delete _books/ estatistica/book/
 
-      - name: Configura Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: "3.13"
+  #     - name: Configura Python
+  #       uses: actions/setup-python@v4
+  #       with:
+  #         python-version: "3.13"
 
-      - name: Instalar dependencias  do python
-        working-directory: estatistica
-        run: |
-          cd book
-          python -m pip install --upgrade pip
-          pip install -r run/requirements.txt          
+  #     - name: Instalar dependencias  do python
+  #       working-directory: estatistica
+  #       run: |
+  #         cd book
+  #         python -m pip install --upgrade pip
+  #         pip install -r run/requirements.txt
 
-      - name: Corrigir links dos <head>
-        working-directory: estatistica
-        run: |
-          cd book
-          python run/cleanBooks.py --base-dir book/ --base-ac build/ac/
+  #     - name: Corrigir links dos <head>
+  #       working-directory: estatistica
+  #       run: |
+  #         cd book
+  #         python run/cleanBooks.py --base-dir book/ --base-ac build/ac/
 
-      - name: Configura credenciais do Git
-        working-directory: estatistica
-        run: |
-          git config user.name "${{ env.USERNAME }}"
-          git config user.email "${{ env.USEREMAIL }}"
-          git remote set-url origin https://x-access-token:${{ env.TOKEN_REPO_SYNC }}@github.com/${{ env.USERNAME }}/estatistica.git
+  #     - name: Configura credenciais do Git
+  #       working-directory: estatistica
+  #       run: |
+  #         git config user.name "${{ env.USERNAME }}"
+  #         git config user.email "${{ env.USEREMAIL }}"
+  #         git remote set-url origin https://x-access-token:${{ env.TOKEN_REPO_SYNC }}@github.com/${{ env.USERNAME }}/estatistica.git
 
-      - name: Faz commit e push dos livros renderizados
-        working-directory: estatistica
-        run: |
-          git add book/
-          git commit -m "books: atualiza books a partir do repo:books" || echo "Nada a commitar"
-          git push --force origin book
+  #     - name: Faz commit e push dos livros renderizados
+  #       working-directory: estatistica
+  #       run: |
+  #         git add book/
+  #         git commit -m "books: atualiza books a partir do repo:books" || echo "Nada a commitar"
+  #         git push --force origin book
 
-  cleanup:
-    needs: [automatizar, estatistica, books]
-    runs-on: ubuntu-latest
-    steps:
-      - name: Deleta artefatos
-        uses: geekyeggo/delete-artifact@v5
-        with:
-          name: |
-            books_renderizados
-            books_detectados
-            books_automatizar
-            github-pages
+  # cleanup:
+  #   needs: [automatizar, estatistica, books]
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Deleta artefatos
+  #       uses: geekyeggo/delete-artifact@v5
+  #       with:
+  #         name: |
+  #           books_renderizados
+  #           books_detectados
+  #           books_automatizar
+  #           github-pages
